plugins {
    id 'java'
    id "com.netflix.dgs.codegen" version "7.0.3"
}

group = 'com.rellevate.connectors.processor'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.3'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.13.3'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.3'


}

generateJava{
    schemaPaths = ["${projectDir}/src/main/resources/schema"] // List of directories containing schema files
    packageName = 'com.example.packagename' // The package name to use to generate sources
    generateClient = true // Enable generating the type safe query API
    typeMapping = ["UnsignedInt": "java.lang.Long", "IdempotencyKey": "java.lang.String"]
}


test {
    useJUnitPlatform()
}